development:
  adapter: postgresql
  encoding: unicode
  database: ruffiansbnb

test:
  adapter: postgresql
  encoding: unicode
  database: ruffiansbnb_test

production:
  adapter: postgresql
  encoding: unicode
  database: ruffiansbnb